// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enabled": boolean;
      "mouseselection": boolean;
      "singlewordmode": boolean;
      "hotkey": string;
      "maxcontext": string;
      "maxexample": string;
      "monolingual": string;
      "preferredaudio": string;
      "services": string;
      "id": string;
      "password": string;
      "duplicate": string;
      "tags": string;
      "deckname": string;
      "typename": string;
      "expression": string;
      "reading": string;
      "extrainfo": string;
      "definition": string;
      "definitions": string;
      "sentence": string;
      "url": string;
      "audio": string;
      "sysscripts": string;
      "udfscripts": string;
      "dictSelected": string;
      "dictNameList": string;
    };
  }
}
